/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ishow_app_uninstall_UnInstallManager */

#ifndef _Included_com_ishow_app_uninstall_UnInstallManager
#define _Included_com_ishow_app_uninstall_UnInstallManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ishow_app_uninstall_UnInstallManager
 * Method:    unInstallStartBrowser
 * Signature: (Ljava/lang/String;ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_ishow_app_uninstall_UnInstallManager_unInstallStartBrowser
  (JNIEnv *, jclass, jstring, jint, jstring, jboolean);

/*
 * Class:     com_ishow_app_uninstall_UnInstallManager
 * Method:    unInstallHttps
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ishow_app_uninstall_UnInstallManager_unInstallHttps
  (JNIEnv *, jclass, jstring, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
